services:
  untilwall-dev:
    container_name: untilwall-dev
    image: 0x3654/untilwall:dev
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./.data:/app/data
    restart: always
